configuration: v0.4.0
image_list:
  tox_levels:
  - 0.0
  - 10.0
  - 30.0
  - 80.0
  forecast_steps: 1.0
  n_steps: 2.0
  minimum_gap: 4.0
  maximum_gap: 10.0
  multisample_weeks: last
  toxins:
  - gtx1
  - gtx4
  - gtx2
  - gtx3
  - dcgtx2
  - dcgtx3
  - gtx5
  - neo
  - dcstx
  - stx
  - c1
  - c2
model:
  balance_val_set: no
  downsample: no
  use_class_weights: no
  dropout1: 0.3
  dropout2: 0.3
  batch_size: 32.0
  units1: 32.0
  units2: 32.0
  epochs: 64.0
  validation_split: 0.2
  shuffle: yes
  num_classes: 4.0
  optimizer: adam
  loss_function: categorical_crossentropy
  model_metrics: categorical_accuracy
train_test:
  split_by: forecast_mode
  train:
    species: mytilus
    region: maine
    year:
    - '2014'
    - '2015'
    - '2016'
    - '2017'
    - '2018'
    - '2019'
    - '2020'
    - '2021'
    - '2022'
    - '2023'
    - '2024'
    - '2025'
  test:
    species: mytilus
    region: maine
    year: '2025'
